const ONE_MINUTE = 60 * 1000;
const ONE_HOUR = 60 * ONE_MINUTE;
const ONE_DAY = 24 * ONE_HOUR;

const SANCTION_CHECK_INTERVAL = ONE_MINUTE;

const DEFAULT_DAILY_LIMIT = 10;
const DEFAULT_LIMIT_WINDOW_SECONDS = 86400;

const DEFAULT_PAGE_SIZE = 20;
const MAX_HISTORY_LIMIT = 10000;

const BLACKLIST_CACHE_KEY_SEPARATOR = ':';

module.exports = {
  ONE_MINUTE,
  ONE_HOUR,
  ONE_DAY,
  SANCTION_CHECK_INTERVAL,
  DEFAULT_DAILY_LIMIT,
  DEFAULT_LIMIT_WINDOW_SECONDS,
  DEFAULT_PAGE_SIZE,
  MAX_HISTORY_LIMIT,
  BLACKLIST_CACHE_KEY_SEPARATOR
};
